apiVersion: v2
appVersion: "latest"
description: Enshrouded - Enshrouded Dedicated Server
name: enshrouded
version: 0.0.4
icon: https://cdn.cloudflare.steamstatic.com/steam/apps/1203620/header.jpg
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2
maintainers:
  - name: Logan Saso
    email: logansaso@gmail.com
