apiVersion: v1
kind: Service
metadata:
  name: {{ include "starrupture.fullname" . }}
  labels:
    {{- include "starrupture.labels" . | nindent 4 }}
  {{- with .Values.starrupture.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.starrupture.service.type }}
  ports:
    - name: game-tcp
      port: {{ .Values.starrupture.server.port }}
      targetPort: {{ .Values.starrupture.server.port }}
      protocol: TCP
      {{- if and (eq .Values.starrupture.service.type "NodePort") .Values.starrupture.service.gameNodePort }}
      nodePort: {{ .Values.starrupture.service.gameNodePort }}
      {{- end }}
    - name: game-udp
      port: {{ .Values.starrupture.server.port }}
      targetPort: {{ .Values.starrupture.server.port }}
      protocol: UDP
      {{- if and (eq .Values.starrupture.service.type "NodePort") .Values.starrupture.service.gameNodePort }}
      nodePort: {{ .Values.starrupture.service.gameNodePort }}
      {{- end }}
    - name: query
      port: {{ .Values.starrupture.server.queryPort }}
      targetPort: {{ .Values.starrupture.server.queryPort }}
      protocol: UDP
      {{- if and (eq .Values.starrupture.service.type "NodePort") .Values.starrupture.service.queryNodePort }}
      nodePort: {{ .Values.starrupture.service.queryNodePort }}
      {{- end }}
  selector:
    {{- include "starrupture.selectorLabels" . | nindent 4 }}
