{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "starrupture.serviceAccountName" . }}
  labels:
    {{- include "starrupture.labels" . | nindent 4 }}
{{- end }}
