{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "voyagers-of-nera.serviceAccountName" . }}
  labels:
    {{- include "voyagers-of-nera.labels" . | nindent 4 }}
{{- end }}
