{{- if and (eq .Values.serverType "tshock") .Values.terraria.tshockSettings }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "terraria.fullname" . }}-tshock-config
  labels:
{{ include "terraria.labels" . | indent 4 }}
type: Opaque
stringData:
  config.json: {{ dict "Settings" .Values.terraria.tshockSettings | toJson | quote }}
{{- end }}
