apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "core-keeper-dedicated-server.fullname" . }}
  labels:
{{ include "core-keeper-dedicated-server.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "core-keeper-dedicated-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "core-keeper-dedicated-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "core-keeper-dedicated-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: WORLD_INDEX
              value: {{ .Values.corekeeper.config.worldIndex | quote }}
            - name: WORLD_NAME
              value: {{ .Values.corekeeper.config.worldName | quote }}
            - name: WORLD_SEED
              value: {{ .Values.corekeeper.config.worldSeed | quote }}
            - name: WORLD_MODE
              value: {{ template "core-keeper-dedicated-server.difficulty" }}
            - name: DATA_PATH
              value: "/home/steam/core-keeper-data"
            - name: MAX_PLAYERS
              value: {{ .Values.corekeeper.config.maxPlayers | quote }}
            {{- if .Values.corekeeper.config.gameID }}
            - name: GAME_ID
              value: {{ .Values.corekeeper.config.gameID | quote }}
            {{- end}}
            {{- if .Values.corekeeper.config.discord.enabled }}
            - name: DISCORD
              value: "1"
            - name: DISCORD_HOOK
              value: {{ .Values.corekeeper.config.discord.webhook | quote }}
            - name: DISCORD_PRINTF_STR
              value: {{ .Values.corekeeper.config.discord.printFormat | quote }}
            {{- else}}
            {{- end}}
            - name: SEASON
              value: {{ .Values.corekeeper.config.seasonOverride | quote }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          tty: {{ .Values.corekeeper.tty }}
          stdin: {{ .Values.corekeeper.stdin }}
          volumeMounts:
          - name: data
            mountPath: /home/steam/core-keeper-data
          - name: config
            mountPath: /home/steam/core-keeper-dedicated
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: data
      {{- if .Values.persistence.data.enabled }}
        {{- if .Values.persistence.data.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.data.existingClaim  }}
         {{- else }}
        persistentVolumeClaim:
          claimName: {{ template "core-keeper-dedicated-server.fullname" .  }}-data
        {{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: config
      {{- if .Values.persistence.config.enabled }}
        {{- if .Values.persistence.config.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.config.existingClaim  }}
        {{- else }}
        persistentVolumeClaim:
            claimName: {{ template "core-keeper-dedicated-server.fullname" .  }}-config
        {{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
