apiVersion: v1
kind: Service
metadata:
  name: {{ include "core-keeper-dedicated-server.fullname" . }}
  labels:
{{ include "core-keeper-dedicated-server.labels" . | indent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "core-keeper-dedicated-server.fullname" . }}
{{- if .Values.corekeeper.service.annotations }}
{{ toYaml .Values.corekeeper.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.corekeeper.service.type }}
  {{- if .Values.corekeeper.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.corekeeper.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: server
      port: {{ .Values.corekeeper.service.port }}
      targetPort: server
      protocol: UDP
    {{- if .Values.corekeeper.service.nodePort }}
      nodePort: {{ .Values.corekeeper.service.nodePort }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "core-keeper-dedicated-server.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
